# Generated by Django 6.0 on 2025-12-06 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookscompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickbooksoauthtoken',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quickbooks.quickbookscompany'),
        ),
    ]
