# Generated by Django 6.0 on 2025-12-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickbookscompany',
            old_name='user',
            new_name='user_account',
        ),
    ]
