# Generated by Django 6.0 on 2025-12-09 05:43

import django.db.models.deletion
import utils.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth2'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='oauth2', max_length=20)),
                ('config', utils.model_utils.EncryptedJSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', utils.model_utils.EncryptedJSONField(blank=True, default=dict)),
                ('provider_data', utils.model_utils.EncryptedJSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integrationprovider')),
            ],
        ),
    ]
