# Generated by Django 6.0 on 2025-12-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(choices=[('Invoice', 'Invoice'), ('Customer', 'Customer')], help_text='Select the entity type, e.g., Invoice, Customer', max_length=50)),
                ('local_field', models.CharField(help_text='Your database field name', max_length=100)),
                ('provider_field', models.CharField(help_text='The field name in the provider API response', max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integrationprovider')),
            ],
            options={
                'verbose_name': 'Field Mapping',
                'verbose_name_plural': 'Field Mappings',
                'unique_together': {('company', 'provider', 'entity_name', 'local_field')},
            },
        ),
    ]
