# Generated by Django 6.0 on 2025-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_providerfieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='provider_identifier',
            field=models.CharField(blank=True, help_text='Unique ID per provider (realm_id, organization_id, tenant_id, etc.)', max_length=255, null=True),
        ),
    ]
