# Generated by Django 6.0 on 2025-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_companyintegration_provider_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyintegration',
            unique_together={('provider', 'provider_identifier')},
        ),
    ]
