# Generated by Django 6.0 on 2025-12-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companymember_user_account'),
        ('integration', '0004_alter_companyintegration_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyintegration',
            unique_together={('company', 'provider'), ('provider', 'provider_identifier')},
        ),
    ]
