# Generated by Django 6.0 on 2025-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_alter_companyintegration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
