# Generated by Django 6.0 on 2025-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ONBOARDING', 'ONBOARDING'), ('PENDING', 'PENDING'), ('IN_REVIEW', 'IN_REVIEW'), ('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('BLOCKED', 'BLOCKED'), ('HOLD', 'HOLD'), ('DEACTIVATED', 'DEACTIVATED'), ('CANCELLED', 'CANCELLED')], default='ONBOARDING', max_length=15),
        ),
    ]
