# Generated by Django 6.0 on 2025-12-10 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companymember_user_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
