"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ajmjrj!u4%_$hmu*o)9&8zxw@co4$s-%jpf2@r#=jf2$yb%9eb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
LOCAL_APPS = [
    'apps.user_account',
    'apps.user_auth',
    'apps.user_profile',
    'apps.integration',
    'apps.customer',
    'apps.invoice',
    'apps.company',

]
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'django_extensions',

]
INSTALLED_APPS += LOCAL_APPS + THIRD_PARTY_APPS
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = "user_account.UserAccount"
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'NON_FIELD_ERRORS_KEY': 'errors',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
QBO_CLIENT_ID = config('QBO_CLIENT_ID')
QBO_CLIENT_SECRET = config('QBO_CLIENT_SECRET')
QBO_REDIRECT_URI = config('QBO_REDIRECT_URI')
QBO_ENVIRONMENT = config('QBO_ENVIRONMENT', default='sandbox')
QBO_SANDBOX_BASE_URL = config("QBO_SANDBOX_BASE_URL", default="https://sandbox-quickbooks.api.intuit.com")
QBO_PRODUCTION_BASE_URL = config("QBO_PRODUCTION_BASE_URL", default="https://quickbooks.api.intuit.com")
QBO_BASE_URL = QBO_SANDBOX_BASE_URL if QBO_ENVIRONMENT.lower() == "sandbox" else QBO_PRODUCTION_BASE_URL

# OAuth config
ZOHO_CLIENT_ID = config("ZOHO_CLIENT_ID")
ZOHO_CLIENT_SECRET = config("ZOHO_CLIENT_SECRET")
ZOHO_REDIRECT_URI = config("ZOHO_REDIRECT_URI")

# Environment (Zoho only has production, but we keep structure)
ZOHO_ENVIRONMENT = config("ZOHO_ENVIRONMENT", default="production")

# Base URLs
ZOHO_ACCOUNTS_BASE_URL = config(
    "ZOHO_ACCOUNTS_BASE_URL",
    default="https://accounts.zoho.com"
)

ZOHO_BOOKS_API_BASE_URL = config(
    "ZOHO_BOOKS_API_BASE_URL",
    default="https://books.zoho.com/api/v3"
)

# Helpful combined URLs
ZOHO_OAUTH_AUTHORIZE_URL = f"{ZOHO_ACCOUNTS_BASE_URL}/oauth/v2/auth"
ZOHO_OAUTH_TOKEN_URL = f"{ZOHO_ACCOUNTS_BASE_URL}/oauth/v2/token"

FERNET_KEY = config("CUSTOM_FERNET_KEY")

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kathmandu"
