from django.db import models


class CompanyStatusChoices(models.TextChoices):
    ONBOARDING = "ONBOARDING", "ONBOARDING"
    PENDING = "PENDING", "PENDING"
    IN_REVIEW = "IN_REVIEW", "IN_REVIEW"
    ACTIVE = "ACTIVE", "ACTIVE"
    ACCEPTED = "ACCEPTED", "ACCEPTED"
    REJECTED = "REJECTED", "REJECTED"
    BLOCKED = "BLOCKED", "BLOCKED"
    HOLD = "HOLD", "HOLD"
    DEACTIVATED = "DEACTIVATED", "DEACTIVATED"
    CANCELLED = "CANCELLED", "CANCELLED"
