# Generated by Django 6.0 on 2025-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255, verbose_name='Customer Id')),
                ('invoice_no', models.CharField(max_length=255, verbose_name='Invoice No')),
                ('invoice_date', models.DateTimeField(verbose_name='Invoice Date')),
                ('invoice_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('invoice_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Invoice Balance')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Discount')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('invoice_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Invoice Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
