# Generated by Django 6.0 on 2025-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active'),
        ('integration', '0001_initial'),
        ('invoice', '0002_invoice_company_invoice_integration_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='', max_length=255, verbose_name='Invoice ID'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'integration_provider', 'invoice_id')},
        ),
    ]
