# Generated by Django 6.0 on 2025-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('sales_tax_id', models.CharField(max_length=255, verbose_name='Sales Tax ID')),
                ('customer_id', models.CharField(max_length=255, verbose_name='Customer ID')),
                ('license_id', models.CharField(max_length=255, verbose_name='License / Permit')),
                ('company_registration_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Registration No')),
                ('duns', models.CharField(blank=True, max_length=255, null=True, verbose_name='DUNS')),
                ('fincen', models.CharField(blank=True, max_length=255, null=True, verbose_name='FINCEN')),
                ('dba', models.CharField(max_length=255, verbose_name='Doing Business As (DBA)')),
                ('tax_id', models.CharField(max_length=255, verbose_name='Federal Tax ID (TIN/EIN)')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('company_email1', models.EmailField(max_length=254, verbose_name='Primary Company Email')),
                ('company_email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Company Email')),
                ('company_contact1', models.CharField(max_length=50, verbose_name='Primary Company Contact')),
                ('company_contact2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secondary Company Contact')),
                ('customer_email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Primary Customer Email')),
                ('customer_email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Customer Email')),
                ('customer_contact1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary Customer Contact')),
                ('customer_contact2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secondary Customer Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
