# Generated by Django 6.0 on 2025-12-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_company'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='integration_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.integrationprovider'),
        ),
        migrations.AddField(
            model_name='customer',
            name='integration_raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
